### ISSUE TITLE
How can you do this?

### ISSUE THREAD

**Issue by reduz** [gfx-rs/portability#23]
How can you work on this if no specification has ever been made public?

**Comment by kvark** [comment]
@reduz I'm a part of the working group :P
The research and experiments we do here reflect directly in the progress and design decisions of the group. So in a way, we aren't as much following the spec as we are building it.

**Comment by reduz** [comment]
That explains. I tried contacting the working group tirelessly all year, despite being a Khronos advisor and could never get a contact from anyone.

I would be very interested in using this in www.godotengine.org, as we are currently using OpenGL ES 3.0 / OpenGL 3.3 and find just terrible driver support for it across the board (they have random bottlenecks everywhere).

**Comment by kvark** [comment]
@reduz 
> That explains. I tried contacting the working group tirelessly all year, despite being a Khronos advisor and could never get a contact from anyone.

I'll be happy to talk about this without disclosing anything secret about the group's work ;)

We (gfx-rs developers and community) have a few Gitter channels, but since you aren't probably interested in the Rust side of things, I created a channel dedicated to C API and this Portability project: https://gitter.im/gfx-rs/portability . If Gitter is not something you'd want to use, we can think of other mediums.

> I would be very interested in using this in www.godotengine.org,

When I read the news about Godot-3, this was exactly what I thought - how great it would be to have it running on next-gen APIs without the cost of maintaining all the backends. Excited to see interest!

**Comment by reduz** [comment]
> I'll be happy to talk about this without disclosing anything secret about the group's work ;)

As mentioned, I signed the NDA with Khronos already and I'm an advisory there.. so I suppose I should be able to join private discussions. I would personally be very interested in attempting to port Godot to this later this year (when I hope it will be a little more stable and the pressure on my side will be less).

I don't mind joining a gitter by then (currently swamped with work on Godot for the 3.0 release)

**Comment by kvark** [comment]
I believe we answered the question in full, closing.
